# Generated by Django 2.0 on 2019-04-28 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='select a assortment for the your post', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('assortment', models.ManyToManyField(help_text='please enter a assortment', to='posts.Assortment')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=25)),
                ('birthDay', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Writer'),
        ),
    ]
