# Generated by Django 2.0 on 2019-05-02 04:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('posts', '0002_postinstance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Post',
        ),
        migrations.RemoveField(
            model_name='postinstance',
            name='post',
        ),
        migrations.DeleteModel(
            name='PostInstance',
        ),
    ]
