# Generated by Django 2.2.7 on 2020-02-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_auto_20200204_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='0', max_length=11),
        ),
    ]
