# Generated by Django 2.2.7 on 2020-02-08 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_auto_20200208_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(default='0', max_length=11, unique=True)),
                ('profile_image', models.ImageField(null=True, upload_to='images/profileimages')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='chatapp.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='chatapp.User'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
