# Generated by Django 2.2.7 on 2020-02-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0008_auto_20200208_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Reg_google',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
