# Generated by Django 2.2.7 on 2020-02-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_user_reg_google'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Reg_google',
            new_name='reg_google',
        ),
    ]
