# Generated by Django 2.2.7 on 2020-07-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0011_auto_20200708_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_read',
            new_name='seen',
        ),
    ]
